### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mylaimani** [ronaldsampaio/USBStreaming#3]
I am getting this error while trying to run the application, any help would be greatly appreciated

Required by:
    project :app
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.github.ronaldsampaio.AndroidUSBCamera:libausbc:v3.4.0-rc1.
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/ronaldsampaio/AndroidUSBCamera/libausbc/v3.4.0-rc1/libausbc-v3.4.0-rc1.pom'.
	at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
	at org.gradle.internal.resource.ResourceExceptions.getFailed(ResourceExceptions.java:57)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadByCoords(DefaultExternalResourceArtifactResolver.java:154)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:94)
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.github.ronaldsampaio.AndroidUSBCamera:libausbc:v3.4.0-rc1.

**Comment by devwithu** [comment]
me too.

**Comment by ronaldsampaio** [comment]
This error is releated with the Jitpack problem. I'll be changing the USBCamera library
